name: control-engineering-with-python
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - scipy
  - autograd
  - sympy
  - matplotlib
  - jupyter
  - rise
  - pandoc=2.1.1
  - curl
  - pip:
    - "-e git+https://github.com/boisgera/pandoc@5077ea22aeae8cbacfb5a2387e3851d07d204ae1#egg=pandoc"


